#!/bin/bash

# check needed tools
tools="aclocal libtoolize autoheader autoconf automake libtool"
for tool in $tools; do
  which $tool > /dev/null || (echo "error, install $tool" && exit 1)
done

# get version
if [ -n "$OVD_VERSION" ]; then
    version="$OVD_VERSION"
else
    if [ -d .svn ]; then
      revision=$(LC_ALL=C svn info . | awk '/^Revision: / {printf "%05d\n", $2}')
    else
      revision=0
    fi
    version="99.99.svn$revision"
fi

sed -e "s/@VERSION@/${version}/g" < configure.ac.in > configure.ac
sed -e "s/@VERSION@/${version}/g" < setup.py.in > setup.py

ln -sfT ../config.c $PWD/sesman/tools/config.c # Why this need ?

autoreconf -fvi
./configure $@
