#!/bin/sh

BZR_VERSION=`bzr version-info |grep revno|sed "s/revno: //g"`

which autoconf
if ! test $? -eq 0
then
  echo "error, install autoconf"
  exit 1
fi

which automake
if ! test $? -eq 0
then
  echo "error, install automake"
  exit 1
fi

which libtool
if ! test $? -eq 0
then
  echo "error, install libtool"
  exit 1
fi

touch configure.ac
touch NEWS
touch AUTHORS
touch README
touch ChangeLog
ln -s ../config.c $PWD/sesman/tools/config.c
sed -e "s/0.5.0/0.5.$BZR_VERSION/g" < configure.ac.in > configure.ac
autoreconf -fvi 

